#! /bin/bash

if [ -z "$1" ] ; then
    echo Usage: $0 PROFILE PROFILE ...
    exit 1
fi

for f in "$@" ; do
    ff=`dirname $f`/`basename $f .profile`
    echo + profile2plot $ff.profile '>' $ff.png
    profile2plot $ff.profile > $ff.png
done